[build]
command = "yarn build"
publish = "ui/dist/"
functions = "api/functions/"
ignore = "git diff --quiet HEAD^..HEAD -- . ':!doc'"

[dev] # https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#netlifytoml-dev-block
command = "yarn start"
publish = "ui/dist/"
autoLaunch = false
targetPort = 8080
