[build]
command = "npm run build"
publish = "build"
functions = "api/functions"

#[functions]
#node_bundler = "esbuild"
#external_node_modules = ["express"]

# Let Netlify functions handle /api/-calls
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

# Webfinger
[[redirects]]
from = "/.well-known/webfinger"
to = "/.netlify/functions/webfinger"
status = 200
force = true

# Mastodon
[[redirects]]
from = "/@rj"
to = "https://mastodon.nl/@rdcl"
status = 301
force = true

# All requests that could not be resolved are routed to the SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Download-Options = "noopen"
X-Frame-Options = "DENY"
X-Permitted-Cross-Domain-Policies = "master-only"
X-XSS-Protection = "1; mode=block"
Strict-Transport-Security = "max-age=63072000; preload"
Permissions-Policy = "interest-cohort=()"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline'"

[[headers]]
for = "/favicon.ico"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"
[headers.values]
Content-Security-Policy = "default-src 'self' 'unsafe-inline'"

[[headers]]
for = "/aoc/*"
[headers.values]
Content-Security-Policy = "default-src 'self' 'unsafe-inline'"

[[headers]]
for = "/rock-paper-scissors/*"
[headers.values]
Content-Security-Policy = "default-src 'self' 'unsafe-inline'"
