[build]
command = "yarn build"
publish = "ui/dist"
functions = "api/functions"
ignore = "git diff --quiet HEAD^..HEAD -- . ':!doc'"

# https://github.com/netlify/cli/issues/2238
#[functions]
#node_bundler = "esbuild"
#external_node_modules = ["express", "pg-native"]

# https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#netlifytoml-dev-block
[dev]
command = "yarn start"
framework = "#custom"
#publish = "ui/public/" # Redirects do not play nice with webpack, let webpack handle redirects for now
autoLaunch = false
targetPort = 8080
