name: CI/CD

on: [push]

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-targets
      - name: Install dependencies
        run: npm clean-install
      - name: Run Linter
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Run Build
        run: npm run build
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npx serve -s build
          wait-on: 'http://localhost:3000'
          # Publishing to cypress has been disabled for now.
          #record: true
          spec: cypress/e2e/**/*.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: http://localhost:3000
# Triggering Netlify deploys has been disabled for now
#      - name: Trigger Netlify Deploy
#        if: success() && github.ref == 'refs/heads/main'
#        run: curl -d '{}' ${{ secrets.NETLIFY_DEPLOY_HOOK }}?trigger_branch=main
