name: CI/CD

on: [push]

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-targets

      - name: Install dependencies
        run: npm clean-install

      - name: Code Style Checks
        run: npm run check

      - name: Build
        run: npm -w www run build

      - name: Integration Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          project: integration-tests
          build: npm -w www run build
          start: npm -w www run preview -- --host
          wait-on: 'http://localhost:4173'
          spec: integration-tests/cypress/e2e/**/*.feature
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: http://localhost:4173
